services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: cli-chatter-server:latest
    container_name: cli-chatter-server
    restart: always
    network_mode: "host"
    environment:
      - server_access_code_=Password # Server password (CHANGE!)
      - server_rooms_=3 # Number of rooms
      - server_packet_limit=10 #Packet limit until authorization(default 5 password attempts).
    volumes:
          - /opt/chatter/report_from_docker.txt:/app/report.txt #Save the report from docker to local file.
    stdin_open: true
    tty: true